name: Daily Stock Price Report

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12:00 UTC
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Generate report
        run: python generate_report.py

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Daily Stock Prices Report
          body: |
            Hi,

            Please find attached the daily stock prices report.

            Best regards,

            Your name
          attachments: |
            ./report.csv
          
  test:
    runs-on: ubuntu-latest
    needs: generate-report

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Test report
        run: python test_report.py
